config/routes.rb
Rails.application.routes.draw do
  get "/404", to: 'errors#not_found'
  get "/422", to: 'errors#unacceptable'
  get "/500", to: 'errors#internal_error'

  resources :wishlists

  patch 'line_items/:id/update_quantity', to: 'line_items#update_quantity', as: 'line_item_update_quantity'
  resources :line_items

  get 'products/search', to: 'products#search', as: 'products_search'
  get 'products/checkout_all', to: 'products#checkout_all', as: 'products_checkout_all'
  patch 'products/:id/add_to_line_items', to: 'products#add_to_line_items', as: 'product_add_to_line_items'
  get 'products/:id/checkout', to: 'products#checkout', as: 'product_checkout'
  patch 'products/:id/add_to_wishlist', to: 'products#add_to_wishlist', as: 'product_add_to_wishlist'

  resources :products
  resources :tags

  get 'pages/home'
  get 'pages/about', as: 'about'
  get 'contact', to: 'pages#contact'
  get 'help', to: 'pages#help'

  root to: 'products#index'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', cart: 'cart' }
end

app/views/shared/_footer.html.erb
<%= stylesheet_link_tag 'footer', media: 'all', 'data-turbolinks-track': 'reload' %>

<footer class="dark-background py-5">
	<div class="container">
		<div class="row">
			<div class="col-lg-2 float-left">
				<h2 class="footer-logo">
					<ul class="lighting-effect cuboid-lighting-effect">
						<li style="animation-delay: 0">C</li>
						<li style="animation-delay: 0.2s">u</li>
						<li style="animation-delay: 0.3s">b</li>
						<li style="animation-delay: 0.4s">o</li>
						<li style="animation-delay: 0.5s">i</li>
						<li style="animation-delay: 0.6s">d</li>
					</ul>
				</h2>

				<div class="footer-social-links py-2">
					<a href="#" class="px-2"><i class="fab fa-facebook"></i></a>
					<a href="#" class="px-2"><i class="fab fa-twitter"></i></a>
					<a href="#" class="px-2"><i class="fab fa-youtube"></i></a>
					<br class="my-2">
					<a href="#" class="px-2"><i class="fab fa-instagram"></i></a>
					<a href="#" class="px-2"><i class="fab fa-linkedin"></i></a>
				</div>
			</div>

			<form class="col-lg-10">
					<div class="row">
						<div class="col-md-3">
							<div class="footer-header">
								Cuboid
							</div>

							<p><a class="footer-link" href="<%= about_path %>">
								<i class="far fa-address-card" style="color: <%= random_colours %>"></i>
								&nbsp;
								About Us
							</a></p>

							<p><a class="footer-link">
								<i class="fas fa-briefcase" style="color: <%= random_colours %>"></i>
								&nbsp;
								Career
							</a></p>

							<p><a class="footer-link">
								<i class="fas fa-book" style="color: <%= random_colours %>"></i>
								&nbsp;
								Our Stories
							</a></p>

							<p><a class="footer-link">
								<i class="fas fa-hands-helping" style="color: <%= random_colours %>"></i>
								&nbsp;
								Help
							</a></p>
						</div>

						<div class="col-md-3">
							<div class="footer-header">
								Policy
							</div>

							<p><a class="footer-link">
								<i class="fas fa-angle-double-right" style="color: <%= random_colours %>"></i>
								&nbsp;
								Return Policy
							</a></p>

							<p><a class="footer-link">
								<i class="fas fa-angle-double-right" style="color: <%= random_colours %>"></i>
								&nbsp;
								Terms of use
							</a></p>

							<p><a class="footer-link">
								<i class="fas fa-angle-double-right" style="color: <%= random_colours %>"></i>
								&nbsp;
								Security
							</a></p>

							<p><a class="footer-link">
								<i class="fas fa-angle-double-right" style="color: <%= random_colours %>"></i>
								&nbsp;
								Terms of Use
							</a></p>

							<p><a class="footer-link">
								<i class="fas fa-angle-double-right" style="color: <%= random_colours %>"></i>
								&nbsp;
								Privacy
							</a></p>

							<p><a class="footer-link">
								<i class="fas fa-angle-double-right" style="color: <%= random_colours %>"></i>
								&nbsp;
								Sitemap
							</a></p>

							<p><a class="footer-link">
								<i class="fas fa-angle-double-right" style="color: <%= random_colours %>"></i>
								&nbsp;
								EPR Compliance
							</a></p>
						</div>

						<div class="col-md-6">
							<div class="footer-header">
								Contact Us
							</div>

							<div class="row">
								<div class="col-md-6">
									<h6>
										<i class="fas fa-envelope-open-text" style="color: <%= random_colours %>"></i>
										&nbsp;
										Mail
									</h6>
									<p>contact@cuboid.com</p>

									<h6>
										<i class="fas fa-phone-alt" style="color: <%= random_colours %>"></i>
										&nbsp;
										Phone
									</h6>
									<p>
										<%= number_to_phone("033#{random_number_generator(7..7)}") %>
									</p>

									<h6>
										<i class="fas fa-comment-alt" style="color: <%= random_colours %>"></i>
										&nbsp;
										Chat
									</h6>

									<p><%= link_to 'Chat with Us', '#', class: "footer-link" %>
								</div>

								<div class="col-md-6">
									<h6>
										<i class="far fa-building" style="color: <%= random_colours %>"></i>
										&nbsp;
										Registered Office
									</h6>
									<%= "#{rand(50..100)} #{random_string_generator}" %>,
									<br>
									<%= random_string_generator %> city,
									<br>
									<%= random_string_generator(8..12).capitalize %>
									<br>
									Post: <%= 8.times.map { rand(9) }.join %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>

		<div class="attribution text-center p-3 copyright">
			Created by Sourav Goswami &copy; 2020. All rights reserved.
		</div>
	</div>
</footer>

app/views/shared/_nav.html.erb
<%= stylesheet_link_tag 'navbar', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'navbar', media: 'all', 'data-turbolinks-track': 'reload' %>

<div id="side-nav">
	<div><a href="#" class="side-nav-item">Hello World</a></div>
	<div><a href="#" class="side-nav-item">Hello World</a></div>
	<div><a href="#" class="side-nav-item">Hello World</a></div>
	<div><a href="#" class="side-nav-item">Hello World</a></div>
	<div><a href="#" class="side-nav-item">Hello World</a></div>
	<div><a href="#" class="side-nav-item">Hello World</a></div>

	<div id="hide-button" onclick="toggleMenu('side-nav', 'side-nav-menu-icon', 'side-nav-menu-id', 'hide-button')">
		&#xab;
	</div>
</div>

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
	<div data-toggle="tooltip" title="Menu" data-placement="bottom" class="side-nav-menu" id="side-nav-menu-id" onclick="toggleMenu('side-nav', 'side-nav-menu-icon', 'side-nav-menu-id', 'hide-button')">
		<span id="side-nav-menu-icon">&#9776;</span>
	</div>

	<div class="navbar-header" data-toggle="tooltip" title="Home" data-placement="bottom">
		<%= link_to root_path, class: "navbar-brand img-link" do %>
			<%= image_tag "cuboid.png", width: "30px" %>
			<span class="smoky-text">
				<span style="animation-delay: 0.1s" class="letters">C</span>&nbsp;
				<span style="animation-delay: 0.2s" class="letters">u</span>&nbsp;
				<span style="animation-delay: 0.3s" class="letters">b</span>&nbsp;
				<span style="animation-delay: 0.4s" class="letters">o</span>&nbsp;
				<span style="animation-delay: 0.5s" class="letters">i</span>&nbsp;
				<span style="animation-delay: 0.6s" class="letters">d</span>
			</span>
		<% end %>
	</div>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon "></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<%= form_tag products_search_path, { method: 'get', class: 'form-inline ml-auto' } do %>
			<div class="input-group">
				<%= text_field_tag :query, params[:query], class: 'form-control input-sm', placeholder: 'Search Products' %>
				<div class="input-group-append">
					<%= submit_tag 'Search', name: nil, class: 'btn btn-light btn-sm' %>
				</div>
			</div>
		<% end %>

		<ul class="nav navbar-nav ml-auto">
			<li class="nav-item" role="button" data-toggle="tooltip" title="Your Wishlist" data-placement="bottom">
				<%= link_to wishlists_path, class: "hover-line nav-link" do %>
					<%= image_tag "wishlist.svg", width: "18px" %>
					Wishlist
				<% end %>
			</li>

			<li class="nav-item"  data-toggle="tooltip" title="Your Cart" data-placement="bottom">
				<%= link_to line_items_path, class: "nav-link hover-line" do %>
					<%= image_tag "cart.svg", width: "18px" %>
					Cart
				<% end %>
			</li>

			<li><a class="break nav-link">|</a></li>

			<li class="nav-item" data-toggle="tooltip" title="Help" data-placement="bottom">
				<a href="<%= help_path %>" class="nav-link hover-line">
					<%= image_tag "account.svg", width: "18px" %>
					Help
				</a>
			</li>

			<li class="nav-item dropdown dropdown-raise" >
				<a class="nav-link dropdown-toggle hover-line" href="#" id="navbarDropdownLanguage" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<%= image_tag "language.svg", width: "18px" %>
					<%= 'En' %>
				</a>

				<div class="dropdown-menu" aria-labelledby="navbarDropdownLanguage">
					<a class="dropdown-item" href="#">English</a>
					<a class="dropdown-item" href="#">Hindi</a>
					<a class="dropdown-item" href="#">Bengali</a>
				</div>
			</li>

			<li class="nav-item dropdown dropdown-raise">
				<a class="nav-link dropdown-toggle hover-line" href="#" id="navbarDropdownAccount" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<%= image_tag "account.svg", width: "18px" %>
					<%= current_user.first_name %>
				</a>

				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownAccount">
					<%= login_helper('dropdown-item') %>
				</div>
			</li>
		</ul>
	</div>
</nav>

	<div id="menu">
		<ul class="menu-ul">
			<li class="dropdown">
				<a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
					Computer
					<span class="caret"></span>
				</a>

				<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
					<% items('computer').each do |x| %>
						<li role="presentation" class="dropdown-header">
							<%= link_to x.product do %>
								<% if x.product.thumbnail.url %>
									<%= image_tag x.product.thumbnail.url, width: '16px' %>
								<% end %>
								<%= x.product.title %>
							<% end %>
						</li>
					<% end %>
				</ul>
			</li>

			<li class="dropdown">
				<a class="dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown">
					Laptops
					<span class="caret"></span>
				</a>

				<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
					<% items('laptops').each do |x| %>
						<li role="presentation" class="dropdown-header">
							<%= link_to x.product do %>
								<% if x.product.thumbnail.url %>
									<%= image_tag x.product.thumbnail.url, width: '16px' %>
								<% end %>
								<%= x.product.title %>
							<% end %>
						</li>
					<% end %>
				</ul>
			</li>

			<li class="dropdown">
				<a class="dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown">
					SBC
					<span class="caret"></span>
				</a>

				<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu3">
					<% items('sbc').each do |x| %>
						<li role="presentation" class="dropdown-header">
							<%= link_to x.product do %>
								<% if x.product.thumbnail.url %>
									<%= image_tag x.product.thumbnail.url, width: '16px' %>
								<% end %>

								<%= x.product.title %>
							<% end %>
						</li>
					<% end %>
				</ul>
			</li>

			<li class="dropdown">
				<a class="dropdown-toggle" type="button" id="dropdownMenu4" data-toggle="dropdown">
					RAM
					<span class="caret"></span>
				</a>

				<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu4">
					<% items('ram').each do |x| %>
						<li role="presentation" class="dropdown-header">
							<%= link_to x.product do %>
								<% if x.product.thumbnail.url %>
									<%= image_tag x.product.thumbnail.url, width: '16px' %>
								<% end %>

								<%= x.product.title %>
							<% end %>
						</li>
					<% end %>
				</ul>
			</li>

			<li class="dropdown">
				<a class="dropdown-toggle" type="button" id="dropdownMenu5" data-toggle="dropdown">
					GPU
					<span class="caret"></span>
				</a>

				<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu5">
					<% items('gpu').each do |x| %>
						<li role="presentation" class="dropdown-header">
							<%= link_to x.product do %>
								<% if x.product.thumbnail.url %>
									<%= image_tag x.product.thumbnail.url, width: '16px' %>
								<% end %>

								<%= x.product.title %>
							<% end %>
						</li>
					<% end %>
				</ul>
			</li>

			<li class="dropdown">
				<a class="dropdown-toggle" type="button" id="dropdownMenu6" data-toggle="dropdown">
					Processors
					<span class="caret"></span>
				</a>

				<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu6">
					<% items('processors').each do |x| %>
						<li role="presentation" class="dropdown-header">
							<%= link_to x.product do %>
								<% if x.product.thumbnail.url %>
									<%= image_tag x.product.thumbnail.url %>
								<% end %>

								<%= x.product.title %>
							<% end %>
						</li>
					<% end %>
				</ul>
			</li>
		</ul>
	</div>

app/views/shared/_previews.html.erb
<div class="container py-2">
	<div id="carousel" class="carousel slide shadow">
		<div class="carousel-inner">
			<% data.each.with_index do |x, i| %>
				<div class="carousel-item <%= 'active' if i == 0 %>">
					<% if x %>
						<div class="img-min-100">
							<%= image_tag x, class: 'img-fluid img-fill' %>
						</div>
					<% end %>
				</div>
			<% end %>

			<a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
				<i class="fa fa-angle-left" aria-hidden="true"></i>
			</a>

			<a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
				<i class="fa fa-angle-right" aria-hidden="true"></i>
			</a>
		</div>

		<ul class="carousel-indicators list-inline mx-auto border px-2">
			<% data.each_with_index do |x, i| %>
				<li class="list-inline-item active">
					<a class="selected" data-slide-to="<%= i %>" data-target="#carousel">
						<% if x %>
							<%= image_tag x, class: "img-fluid" %>
						<% end %>
					</a>
				</li>
			<% end %>
		</ol>
	</div>
</div>

app/views/shared/_tagged_products.html.erb
<% tag.product.tap do |x| %>
	<div class="col-sm-6 col-md-4 mb-4">
		<div class="card">
			<%= link_to x do %>
				<div class="img-hover-effect">
					<div class="img-hover-label">
						<i class="fas fa-info-circle"></i>
						More Info
					</div>

					<% if x.thumbnail.url %>
						<%= image_tag x.thumbnail.url, class: 'card-img-top' %>
					<% else %>
						<div class="no-img-label">No Preview Available!</div>
					<% end %>
				</div>
			<% end %>

			<div class="card-body">
				<h5 class="card-title"><%= x.title %></h5>
				<p class="card-text"><%= x.description.to_s %></p>

				<p class="card-text">
					<%= format_tags(x, 'tags:', tag.title).html_safe %>
				</p>

				<a href="#" class="btn-outline-primary-animated" data-content="Add to Cart"></a>
				<a href="#" class="btn-outline-success-animated" data-content="Checkout"></a>
				<a href="#" class="btn-outline-warning-animated" data-content="Buy Later"></a>
			</div>
		</div>
	</div>
<% end %>