config/routes.rb
Rails.application.routes.draw do
  get "/404", to: 'errors#not_found'
  get "/422", to: 'errors#unacceptable'
  get "/500", to: 'errors#internal_error'

  resources :wishlists

  patch 'line_items/:id/update_quantity', to: 'line_items#update_quantity', as: 'line_item_update_quantity'
  resources :line_items

  get 'products/search', to: 'products#search', as: 'products_search'
  get 'products/checkout_all', to: 'products#checkout_all', as: 'products_checkout_all'
  patch 'products/:id/add_to_line_items', to: 'products#add_to_line_items', as: 'product_add_to_line_items'
  get 'products/:id/checkout', to: 'products#checkout', as: 'product_checkout'
  patch 'products/:id/add_to_wishlist', to: 'products#add_to_wishlist', as: 'product_add_to_wishlist'

  resources :products
  resources :tags

  get 'pages/home'
  get 'pages/about', as: 'about'
  get 'contact', to: 'pages#contact'
  get 'help', to: 'pages#help'

  root to: 'products#index'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', cart: 'cart' }
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.where(user_id: current_user.id)
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
  end

  # GET /wishlists/new
  def new
    @wishlist = Wishlist.new
  end

  # GET /wishlists/1/edit
  def edit
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    @wishlist = Wishlist.new(wishlist_params)

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully created.' }
        format.json { render :show, status: :created, location: @wishlist }
      else
        format.html { render :new }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlists/1
  # PATCH/PUT /wishlists/1.json
  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @wishlist }
      else
        format.html { render :edit }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @wishlist.destroy
    respond_to do |format|
      format.html { redirect_to wishlists_url, notice: 'Wishlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wishlist_params
      params.require(:wishlist).permit(:product_id, :user_id)
    end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.erb
<%= form_with(model: wishlist, local: true) do |form| %>
  <% if wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
        <% wishlist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<center><h2>Your Wishlist</h2></center>

<div id="item-thumbnails">
	<div class="row">
		<div class="col-md-6 col-sm-12 col-lg-4">
			<% @wishlists.each.with_index do |x, i| %>
				<div class="card">
					<div class="card-body">
						<%= link_to x.product do %>
							<div class="img-hover-effect">
								<div class="img-hover-label">
									<i class="fas fa-info-circle"></i>
									More Info
								</div>

								<% if x.product.thumbnail.url %>
									<%= image_tag x.product.thumbnail.thumbnail!.url, class: 'card-img-top' %>
								<% else %>
									<div class="no-img-label">No Preview Available!</div>
								<% end %>
							</div>
						<% end %>

						<h3 class="card-title"><%= x.product.title %></h3>
						<h5 class="card-title">Price: <%= rs_tag(x.product.price) %></h5>
						<h6 class="card-text"><%= x.product.description.to_s %></h6>

						<p class="card-text">
							<%= format_tags(x.product, 'tags:').html_safe %>
						</p>

						<%= link_to product_add_to_line_items_path(x.product), method: :patch, remote: true, class: "btn-outline-primary-animated", 'data-content': "Add to Cart" do %>
							<%= image_tag 'cart-button.svg', width: '24px' %>
						<% end %>

						<%= link_to line_items_path, class: "btn-outline-success-animated", 'data-content': "Checkout" do %>
							<%= image_tag 'purchase.svg', width: '24px' %>
						<% end %>

						<%= link_to x, method: :delete, class: "btn-outline-warning-animated", 'data-content': "Remove", data: { confirm: 'Are you sure?' } do %>
							<%= image_tag 'wishlist-remove.svg', width: '24px' %>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>

		<div class="col-md-2 col-lg-4 col-sm-0">
		</div>

		<div class="col-md-4 col-lg-4 col-sm-12">
			<h4>Other items you might be interested in:</h4>
			<% user_top_suggested_tags(3).each do |x| %>
				<%= link_to x, class: 'link-no-style' do %>
					<div class="card mb-3">
						<div class="card-body">
							<div class="img-hover-effect">
								<div class="img-hover-label">
									<i class="fas fa-info-circle"></i>
									More Info
								</div>

								<% if x.thumbnail.url %>
									<%= image_tag x.thumbnail.thumbnail!.url, class: 'card-img-top' %>
								<% else %>
									<div class="no-img-label">No Preview Available!</div>
								<% end %>
							</div>

							<div style="font-weight: 1000 ; font-size: 20px"><%= x.title %></div>
							<%= rs_tag(x.product.price) %>

							<%= x %>
							<div class="rating-wrapper-all">
								<div class="rating-wrapper">
									<div class="rating-div"></div>
									<%= image_tag 'stars.png', class: 'rating' %>
								</div>

								<span class="ratings-label">134</span>
							</div>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/wishlists/new.html.erb
<h1>New Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<p>
  <strong>Product:</strong>
  <%= @wishlist.product_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @wishlist.user_id %>
</p>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>