config/routes.rb
Rails.application.routes.draw do
  get "/404", to: 'errors#not_found'
  get "/422", to: 'errors#unacceptable'
  get "/500", to: 'errors#internal_error'

  resources :wishlists

  patch 'line_items/:id/update_quantity', to: 'line_items#update_quantity', as: 'line_item_update_quantity'
  resources :line_items

  get 'products/search', to: 'products#search', as: 'products_search'
  get 'products/checkout_all', to: 'products#checkout_all', as: 'products_checkout_all'
  patch 'products/:id/add_to_line_items', to: 'products#add_to_line_items', as: 'product_add_to_line_items'
  get 'products/:id/checkout', to: 'products#checkout', as: 'product_checkout'
  patch 'products/:id/add_to_wishlist', to: 'products#add_to_wishlist', as: 'product_add_to_wishlist'

  resources :products
  resources :tags

  get 'pages/home'
  get 'pages/about', as: 'about'
  get 'contact', to: 'pages#contact'
  get 'help', to: 'pages#help'

  root to: 'products#index'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', cart: 'cart' }
end

app/models/product.rb
class Product < ApplicationRecord
	before_destroy :not_referenced_by_any_line_item
	# before_action :authneticate_user!
	belongs_to :user, optional: true

	# validates :title, :price, :features, presence: true
	# validates :description, length: { maximum: 1500, too_long: "Maximum %{count} characters are allowed}", minimum: 6, too_short: "Minimum %{count} characters are required" }
	# validates :title, length: { maximum: 64, too_long: "Maximum %{count} characters are allowed" }
	# validates :price, length: { maximum: 6 }
	# validates_presence_of :main_image, :thumbnail

	mount_uploader :thumbnail, ProductUploader
	mount_uploader :main_image, ProductUploader

	has_many :tags
	has_many :line_items
	has_many :wishlists
	has_many :reviews
	has_many :previews
	has_many :purchases

	accepts_nested_attributes_for :previews,
		allow_destroy: true,
		reject_if: ->attrs { attrs['image'].blank? }

	accepts_nested_attributes_for :reviews,
	allow_destroy: true,
	reject_if: ->attrs { attrs['rating'].blank? }

	private
	def not_referenced_by_any_line_item
		unless line_items.empty?
			errors.add(:base, 'Line items present')
			throw :abort
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only: [:show, :edit, :update, :destroy, :reviews, :add_to_line_items, :checkout, :add_to_wishlist]
	before_action :authenticate_user!, except: [:index, :show, :add_to_line_items, :add_to_wishlist]
	access all: [:show, :index], user: { except: [:destroy, :edit, :new] }, site_admin: :all

	# GET /products
	# GET /products.json
	def index
		@products = Product.order('created_at desc').page(params[:page]).per(20)
		# ('created_at desc').page(5)
	end

	# GET /products/1
	# GET /products/1.json
	def show
		@ratings = @product.reviews
		@n_ratings = @ratings.count
		@ratings_avg = @ratings.map(&:rating).sum / @n_ratings
	end

	def reviews
	end

	def checkout
		@ratings = @product.reviews
		@n_ratings = @ratings.count
		@ratings_avg = @ratings.map(&:rating).sum / @n_ratings
	end

	def checkout_all
		@line_items = current_user.line_items.keys
		@products = @line_items.to_a
		@avg_ratings = @products.map(&:reviews).map { |x| r = x.map(&:rating).sum / x.length }
		@total_price = @products.map(&:price).sum
	end

	# PATCH /products/1
	def add_to_line_items
		if current_user.is_a?(GuestUser)
			respond_to do |format|
				format.js { render 'sign_in_to_continue' }
			end
		else
			@line_item = LineItem.new(user_id: current_user.id, product_id: @product.id)

			respond_to do |format|
				if @line_item.save
					format.js
				else
					format.js { render 'failed_saving_cart_item' }
				end
			end
		end
	end

	def add_to_wishlist
		if current_user.is_a?(GuestUser)
			respond_to do |format|
				format.js { render 'sign_in_to_continue' }
			end
		else
			if Wishlist.where(product_id: @product.id).empty?
				@wishlist = Wishlist.new(user_id: current_user.id, product_id: @product.id)

				respond_to do |format|
					if @wishlist.save
						format.js
					else
						format.js { render 'failed_adding_wishlist' }
					end
				end
			# elsif !current_user
			else
				respond_to do |format|
					format.js { render 'already_added_to_wishlist' }
				end
			end
		end
	end

	# GET /products/new
	def new
		@product = Product.new
		@product.previews.build
		@product
	end

	# GET /products/1/edit
	def edit
	end

	# POST /products
	# POST /products.json
	def create
		@product = Product.new(product_params)

		respond_to do |format|
			if @product.save
				format.html { redirect_to @product, notice: 'Product was successfully created.' }
				format.json { render :show, status: :created, location: @product }
			else
				format.html { render :new }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /products/1
	# PATCH/PUT /products/1.json
	def update
		respond_to do |format|
			if @product.update(product_params)
				format.html { redirect_to @product, notice: 'Product was successfully updated.' }
				format.json { render :show, status: :ok, location: @product }
			else
				format.html { render :edit }
				format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end

	# GET /products/search
	def search
		@search_term = params[:query].to_s
		if @search_term.empty?
		else
			@results = Product.where('lower(title) like ?', "%#{@search_term}%")
			@count = @results.count
			@paginated = @results.page(params[:page]).per(6)
		end
	end

	# DELETE /products/1
	# DELETE /products/1.json
	def destroy
		@product.destroy
		respond_to do |format|
			format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_product
			@product = Product.find(params[:id])
		end


		# Only allow a list of trusted parameters through.
		def product_params
			params.require(:product).permit(
				:title, :description, :price,
				:features, :main_image, :thumbnail,
				previews_attributes: [:id, :image],
				reviews_attributes: [:id, :comment, :rating]
			)
		end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |f| %>
	<% if product.errors.any? %>
		<div id="error_explanation">
			<%=
				alert_generator(
					%[#{pluralize(product.errors.count, "error")} prohibited this product from being saved]
				)
			%>

			<% product.errors.full_messages.each do |message| %>
				<%= alert_generator(message) %>
			<% end %>
		</div>
	<% end %>

	<div class="body-wrapper-flex">
		<div class="card w-90 shadow rounded">
			<div class="card-body">
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<%= f.label :title %>
							<%= f.text_field :title, class: 'form-control' %>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :description %>
							<%= f.text_area :description, class: 'form-control' %>
						</div>
					</div>

					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :features %>
							<%= f.text_area :features, class: 'form-control' %>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="field">
							<%= f.label :price %>
							<%= f.text_field :price, class: 'form-control' %>
						</div>
					</div>
				</div>

				<br>

				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<%= f.label :main_image %>
							<br>
							<%= f.file_field :main_image %>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<%= f.label :thumbnail %>
							<br>
							<%= f.file_field :thumbnail %>
						</div>
					</div>
				</div>

				<%= f.fields_for :previews do |preview_form| %>
					<%= render 'preview_fields', f: preview_form %>
				<% end %>

				<div class="col-md-12">
					<%= link_to_add_association '', f, :previews, class: 'btn-outline-danger-animated', 'data-content': '&#x002B; Add More Previews'.html_safe %>
				</div>

				<div class="row">
					<div class="col-md-12">
						<label class="btn-outline-warning-animated" data-content="&#x2713;submit">
							<%= f.submit '', style: 'display: none' %>
						</label>
					</div>
				</div>

				<div class="row">
					<div class="col-md-4">
						<%= link_to '', products_path, class: 'btn-outline-info-animated', 'data-content': "&#x276E; Back".html_safe %>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/products/_preview_fields.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="form-group">
			<%= f.label :image %>
			<%= f.file_field :image %>
		</div>
	</div>
</div>

app/views/products/add_to_line_items.js.erb
notify("<%= @product.title %> added to cart", 'View Cart', "<%= line_items_path %>")

app/views/products/add_to_wishlist.js.erb
notify("<%= @product.title %> added to wishlist", 'View Wishlist', "<%= wishlists_path %>")

app/views/products/already_added_to_wishlist.js.erb
notify("<%= @product.title %> was already added to wishlist", 'View Wishlist', "<%= wishlists_path %>")

app/views/products/checkout.html.erb
<%= link_to '', products_path, class: 'btn-outline-purple-animated', 'data-content': 'back' %>

<div class="row mb-5">
	<div class="col-md-2">
	</div>

	<div class="col-md-4">
		<div class="shadow-sm-hover">
			<div class="card overflow-hide">
				<div class="card-body">
					<form class="form-group">
						<div class="mt-4">
							<h2>Checkout</h2>
							Pay <%= rs_tag(@product.price) %>
						</div>

						<div class="swap-flip">
							<div class="mt-4">
								Card Type <br>

								<select class="form-control">
									<option>Visa</option>
									<option>Master Card</option>
									<option>RuPay</option>
								</select>
							</div>

							<div class="mt-4">
								<label for="dummyInput1">Name on Card</label>
								<input type="text" class="form-control" id="dummyInput1" placeholder="Name">
							</div>

							<div class="mt-4">
								<label for="dummyInput1">Credit/Debit Card Number</label>
								<input type="text" class="form-control" placeholder="Credit/Debit Card Number">
							</div>

							<div class="mt-4">
								Expiration Date
								<div class="row">
									<div class="col-md-4">
										<select class="form-control" id="monthPicker"></select>
									</div>

									<div class="col-md-4">
										<select class="form-control" id="yearPicker"></select>
									</div>
								</div>
							</div>

							<div class="mt-4">
								<label for="dummyInput1">CVV Number</label>
								<input type="text" class="form-control" id="dummyInput1" placeholder="CVV">
							</div>
						</div>

						<div class="swap-flop">
							Delivery Address
							<div class="mt-4">
								<% 3.times do |i| %>
									<label for="dummyInput1" class="mt-2">Delivery Adress Line <%= i.next %></label>
									<input type="text" class="form-control" id="dummyInput1" placeholder="Address Line <%= i.next %>">
								<% end %>
							</div>

							<div class="mt-4">
								<label for="dummyInput1">City</label>
								<input type="text" class="form-control">
							</div>

							<div class="mt-4">
								<label for="dummyInput1">Pin Code</label>
								<input type="text" class="form-control">
							</div>

							<div class="mt-4">
								<label for="dummyInput1">State</label>
								<select class=" form-control"></select>
							</div>
						</div>

						<div class="mt-4" class="swap-flip">
							<center>
								<div class="swap-flip">
									<%= link_to '', '', class: 'btn-outline-purple-animated', 'data-content': 'Continue', remote: true %>
								</div>

								<div class="swap-flop">
									<%= link_to '', '', class: 'btn-outline-pink-animated', 'data-content': 'Confirm', remote: true %>
								</div>
							<center>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<%= link_to product_path(@product) do %>
			<%=
				render 'shared/previews',
				data: [
					@product.main_image.thumbnail!.url, @product.thumbnail.thumbnail!.url,
					*@product.previews.map { |x| x.image.thumbnail!.url }
				]
			%>

			<h1><%= @product.title %></h1>
			<p>By <%= 'AKG' %></p>

			<p>
				<% unless @product.tags.empty? %>
					Tags: <%= format_tags(@product, 'tags:').html_safe %>
				<% else %>
					Tags: No tags are associated with this product!
				<% end %>
			</p>

			<p>
				<%= rating_gen(@ratings_avg).html_safe %>

				<%= link_to '', '#', class: 'links',
					'data-content': %Q[#{@n_ratings} Review#{@n_ratings != 1 ? 's' : '' }].html_safe
				%>
			</p>
			<hr>

			<% if @product.price == @product.price %>
				Price: Rs. <%= @product.price %>
			<% elsif @product.price < @product.price %>
				MRP. Rs. <strike><%= @product.price %></strike><br>
				Price: Rs. <%= @product.price %>
			<% end %>

			<br>
			<br>
		<% end %>
	</div>
</div>

app/views/products/checkout.js.erb
$(() => {
	$('.swap-flip').css('animation', 'slideout 0.5s ease forwards').fadeOut(500)

	setInterval(() => {
		$('.swap-flop').css('animation', 'slidein 0.25s ease forwards').css('display', 'block')
	}, 500)
})

app/views/products/checkout_all.html.erb
<%= link_to '', products_path, class: 'btn-outline-purple-animated', 'data-content': 'back' %>

<div class="row mb-5">
	<div class="col-md-2">
	</div>

	<div class="col-md-4">
		<div class="shadow-sm-hover">
			<div class="card overflow-hide">
				<div class="card-body">
					<form class="form-group">
						<div class="mt-4">
							<h2>Checkout</h2>
							Pay <%= rs_tag(@total_price) %>
						</div>

						<div class="swap-flip">
							<div class="mt-4">
								Card Type <br>

								<select class="form-control">
									<option>Visa</option>
									<option>Master Card</option>
									<option>RuPay</option>
								</select>
							</div>

							<div class="mt-4">
								<label for="dummyInput1">Name on Card</label>
								<input type="text" class="form-control" id="dummyInput1" placeholder="Name">
							</div>

							<div class="mt-4">
								<label for="dummyInput1">Credit/Debit Card Number</label>
								<input type="text" class="form-control" placeholder="Credit/Debit Card Number">
							</div>

							<div class="mt-4">
								Expiration Date
								<div class="row">
									<div class="col-md-4">
										<select class="form-control" id="monthPicker"></select>
									</div>

									<div class="col-md-4">
										<select class="form-control" id="yearPicker"></select>
									</div>
								</div>
							</div>

							<div class="mt-4">
								<label for="dummyInput1">CVV Number</label>
								<input type="text" class="form-control" id="dummyInput1" placeholder="CVV">
							</div>
						</div>

						<div class="swap-flop">
							Delivery Address
							<div class="mt-4">
								<% 3.times do |i| %>
									<label for="dummyInput1" class="mt-2">Delivery Adress Line <%= i.next %></label>
									<input type="text" class="form-control" id="dummyInput1" placeholder="Address Line <%= i.next %>">
								<% end %>
							</div>

							<div class="mt-4">
								<label for="dummyInput1">City</label>
								<input type="text" class="form-control">
							</div>

							<div class="mt-4">
								<label for="dummyInput1">Pin Code</label>
								<input type="text" class="form-control">
							</div>

							<div class="mt-4">
								<label for="dummyInput1">State</label>
								<select class=" form-control"></select>
							</div>
						</div>

						<div class="mt-4" class="swap-flip">
							<center>
								<div class="swap-flip">
									<%= link_to '', '', class: 'btn-outline-purple-animated', 'data-content': 'Continue', remote: true %>
								</div>

								<div class="swap-flop">
									<%= link_to '', '', class: 'btn-outline-pink-animated', 'data-content': 'Confirm', remote: true %>
								</div>
							<center>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<% @products.each_with_index do |x, i| %>
			<%= link_to product_path(x) do %>
				<% if x.main_image.thumbnail!.url %>
					<%=
							render 'shared/previews',
							data: [
								x.main_image.thumbnail!.url, x.thumbnail.thumbnail!.url,
								*x.previews.map { |x| x.image.thumbnail!.url }
							]
					%>
				<% end %>

				<h1><%= x.title %></h1>
				<p>By <%= 'AKG' %></p>

				<p>
					<% unless x.tags.empty? %>
						Tags: <%= format_tags(x, 'tags:').html_safe %>
					<% else %>
						Tags: No tags are associated with this product!
					<% end %>
				</p>

				<p>
					<%= rating_gen(@avg_ratings.at(i)).html_safe %>

					<%#= link_to '', '#', class: 'links',
						'data-content': %Q[#{x.reviews} Review#{x.reviews != 1 ? 's' : '' }].html_safe
					%>
				</p>
				<hr>

				<% if x.price == x.price %>
					Price: <%= rs_tag(x.price) %>
				<% elsif x.price < x.price %>
					MRP. <strike><%= price_tag(x.price) %></strike><br>
					Price: <%= price_tag(x.price) %>
				<% end %>
				<br>
				<br>
			<% end %>
		<% end %>
	</div>

<%
=begin%>
		<%= link_to product_path(x) do %>
			<%=
				render 'shared/previews',
				data: [
					x.main_image.thumbnail!.url, @product.thumbnail.thumbnail!.url,
					*@product.previews.map { |x| x.image.thumbnail!.url }
				]
			%>

<%
=end %>
	</div>
</div>

app/views/products/checkout_all.js.erb
$(() => {
	$('.swap-flip').css('animation', 'slideout 0.5s ease forwards').fadeOut(500)

	setInterval(() => {
		$('.swap-flop').css('animation', 'slidein 0.25s ease forwards').css('display', 'block')
	}, 500)
})

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/failed_adding_wishlist.js.erb
notify("Error: <%= @product.title %> cannot be added to wishlist!", 'View Product', "<%= product_path %>")

app/views/products/failed_saving_cart_item.js.erb
notify("Error: <%= @product.title %> cannot be added to cart!", 'View Product', "<%= product_path %>")

app/views/products/index.html.erb
<div class="container-fluid" id="contents px-0">
	<div id="head-wrap">
		<div id="heading">
			Welcome to Cuboid...%-%Your Digital Computer Store...%-%We Offer High Quality Products...
		</div>
		<span id="caret">|</span>
	</div>

	<% if logged_in?(:site_admin) %>
		<center><%= link_to 'New Product', new_product_path %></center>
	<% end %>

	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
		<ol class="carousel-indicators">
			<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
			<li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
		</ol>

		<div class="carousel-inner">
			<div class="carousel-item active">
				<%= image_tag 'carousel-images/1.jpg', class: 'd-block w-100' %>
			</div>

			<div class="carousel-item">
				<%= image_tag 'carousel-images/2.jpg', class: 'd-block w-100' %>
			</div>

			<div class="carousel-item">
				<%= image_tag 'carousel-images/3.jpg', class: 'd-block w-100' %>
			</div>

			<div class="carousel-item">
				<%= image_tag 'carousel-images/4.jpg', class: 'd-block w-100' %>
			</div>

			<div class="carousel-item">
				<%= image_tag 'carousel-images/5.jpg', class: 'd-block w-100' %>
			</div>

			<div class="carousel-item">
				<%= image_tag 'carousel-images/6.jpg', class: 'd-block w-100' %>
			</div>
		</div>

		<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>

		<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>

	<div class="separator-wrapper">
		<div class="separator">
			Hot Sales
		</div>
	</div>

	<%# Items Card %>
	<div id="item-thumbnails">
		<div class="row">
			<% @products.each do |x| %>
				<div class="col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-4">
					<div class="card">
						<%= link_to x do %>
							<div class="img-hover-effect">
								<div class="img-hover-label">
									<i class="fas fa-info-circle"></i>
									More Info
								</div>

								<% if x.thumbnail.url %>
									<%= image_tag x.thumbnail.thumbnail!.url, class: 'card-img-top' %>
								<% else %>
									<div class="no-img-label">No Preview Available!</div>
								<% end %>
							</div>
						<% end %>

						<div class="card-body">
							<h3 class="card-title"><%= x.title %></h3>
							<h5 class="card-title">Price: <%= rs_tag(x.price) %></h5>
							<h6 class="card-text"><%= x.description.to_s %></h6>

							<p class="card-text">
								<%= format_tags(x, 'tags:').html_safe %>
							</p>

							<%= link_to product_add_to_line_items_path(x), remote: true, method: :patch, class: 'btn-outline-blue-animated', 'data-content': 'Add to Cart' do %>
								<%= image_tag('cart-button.svg', width: '24px') + "&nbsp;&nbsp".html_safe %>
							<% end %>

							<%= link_to product_checkout_path(x), method: :get, class: 'btn-outline-pink-animated', 'data-content': 'Buy Now' do %>
								<%= image_tag('purchase.svg', width: '24px') + "&nbsp;&nbsp".html_safe  %>
							<% end %>

							<%= link_to product_add_to_wishlist_path(x), remote: true, method: :patch, class: "btn-outline-warning-animated", 'data-content': "Buy Later" do %>
								<%= image_tag('wishlist.svg', width: '24px') + "&nbsp;&nbsp".html_safe %>
							<% end %>

							<%#= Admin Actions %>
							<%if logged_in?(:site_admin) %>
								<hr>

								<div class="admin-section">
									<%= image_tag 'diamond.svg', height: '40px' %>
									<span class="centrify-v height-36">Admin Actions</span>
								</div>

								<br>

								<%= link_to edit_product_path(x), class: 'btn-outline-pink-animated', 'data-content': 'Edit' do %>
									<%= image_tag('pencil.svg', width: '24px') + '&nbsp;&nbsp;'.html_safe %>
								<% end %>

								<%= link_to x, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-outline-emerald-animated', 'data-content': 'Trashify' do %>
									<%= image_tag('trash.svg', width: '24px') + '&nbsp;&nbsp;'.html_safe %>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>

	<div class="centrify">
		<%= paginate @products, class: 'pagination' %>
	</div>
</div>

<%= javascript_pack_tag 'home_body.js' %>

app/views/products/show.html.erb
<%= link_to '', products_path, class: 'btn-outline-purple-animated', 'data-content': 'back' %>
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-4">
		<%=
			render 'shared/previews',
			data: [
				@product.main_image.thumbnail!.url, @product.thumbnail.thumbnail!.url,
				*@product.previews.map { |x| x.image.thumbnail!.url }
			]
		%>
	</div>

	<div class="col-md-6">
		<h1><%= @product.title %></h1>
		<p>By <%= 'AKG' %></p>

		<p>
			<% unless @product.tags.empty? %>
				Tags: <%= format_tags(@product, 'tags:').html_safe %>
			<% else %>
				Tags: No tags are associated with this product!
			<% end %>
		</p>

		<p>
			<%= rating_gen(@ratings_avg).html_safe %>

			<%= link_to '', '#', class: 'links',
				'data-content': %Q[#{@n_ratings} Review#{@n_ratings != 1 ? 's' : '' }].html_safe
			%>
		</p>
		<hr>

		<% if @product.price == @product.price %>
			Price: <%= rs_tag(@product.price) %>
		<% elsif @product.price < @product.price %>
			MRP. <strike><%= rs_tag(@product.price) %></strike><br>
			Price: <%= rs_tag(@product.price) %>
		<% end %>

		<br>
		<br>

		<h5>Description</h5>
		<div class="break-word-wrapper"><%= @product.description %></div>

		<br>
		<br>

		<h5>Features</h5>
		<div class="break-word-wrapper"><%= @product.features %></div>

		<%= link_to product_checkout_path(@product), method: :get, class: 'btn-outline-pink-animated', 'data-content': 'Buy Now' do %>
			<%= image_tag('purchase.svg', width: '24px') + "&nbsp;&nbsp".html_safe %>
		<% end %>

		<%= link_to product_add_to_line_items_path(@product), remote: true, method: :patch, class: 'btn-outline-blue-animated', 'data-content': 'Add to Cart' do %>
			<%= image_tag('cart-button.svg', width: '24px') + "&nbsp;&nbsp".html_safe %>
		<% end %>

		<%= link_to product_add_to_wishlist_path(@product), remote: true, method: :patch, class: 'btn-outline-warning-animated', 'data-content': 'Add to Wishlist' do %>
			<%= image_tag('wishlist.svg', width: '24px') + "&nbsp;&nbsp".html_safe %>
		<% end %>

		<%if logged_in?(:site_admin) %>
			<hr>

			<div class="admin-section">
				<%= image_tag 'diamond.svg', height: '40px' %>
				<span class="centrify-v height-36">Admin Actions</span>
			</div>

			<br>

			<%= link_to edit_product_path(@product), class: 'btn-outline-pink-animated', 'data-content': 'Edit' do %>
				<%= image_tag('pencil.svg', width: '24px') + '&nbsp;&nbsp;'.html_safe %>
			<% end %>

			<%= link_to @product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-outline-emerald-animated', 'data-content': 'Trashify' do %>
				<%= image_tag('trash.svg', width: '24px') + '&nbsp;&nbsp;'.html_safe %>
			<% end %>
		<% end %>
	</div>
</div>

<hr>

<h2>Reviews and Ratings</h2>
<% @ratings.each do |x| %>
	<%= x.user.name %><br>
	<%= rating_gen(x.rating).html_safe %>
	"<%= x.comment %>"
	<br>
	<br>
<% end %>