config/routes.rb
Rails.application.routes.draw do
  get "/404", to: 'errors#not_found'
  get "/422", to: 'errors#unacceptable'
  get "/500", to: 'errors#internal_error'

  resources :wishlists

  patch 'line_items/:id/update_quantity', to: 'line_items#update_quantity', as: 'line_item_update_quantity'
  resources :line_items

  get 'products/search', to: 'products#search', as: 'products_search'
  get 'products/checkout_all', to: 'products#checkout_all', as: 'products_checkout_all'
  patch 'products/:id/add_to_line_items', to: 'products#add_to_line_items', as: 'product_add_to_line_items'
  get 'products/:id/checkout', to: 'products#checkout', as: 'product_checkout'
  patch 'products/:id/add_to_wishlist', to: 'products#add_to_wishlist', as: 'product_add_to_wishlist'

  resources :products
  resources :tags

  get 'pages/home'
  get 'pages/about', as: 'about'
  get 'contact', to: 'pages#contact'
  get 'help', to: 'pages#help'

  root to: 'products#index'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', cart: 'cart' }
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :product
	belongs_to :user

	def total_price
		product.price.to_i * quantity.to_i
	end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
	include CurrentCart

	before_action :set_line_item, only: [:show, :edit, :update, :destroy]
	before_action :set_current_user, only: [:index]
	before_action :set_cart, only: [:create]

	# GET /line_items
	# GET /line_items.json
	def index
		@line_items = LineItem.where(user_id: current_user)

		@user_items = @line_items
			.map { |x| p [Product.find(x.product_id), x.quantity, x] }.group_by { |x| x[0] }
			.reduce( {} ) { |h, x| h.merge!({ x[0] => [ x[1].map { |y| y[1] }.sum, x[1].map(&:last) ] }) }
	end

	# GET /line_items/1
	# GET /line_items/1.json
	def show
	end

	def update_quantity
		# byebug
	end

	# GET /line_items/new
	def new
		@line_item = LineItem.new
	end

	# GET /line_items/1/edit
	def edit
	end

	# POST /line_items
	# POST /line_items.json
	def create
		@product = Product.find(params[:product_id])
		@line_item = @cart.add_product(@product)

		respond_to do |format|
			if @line_item.update(line_item_params)
				format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
				format.json { render :show, status: :ok, location: @line_item }
			else
				format.html { render :edit }
				format.json { render json: @line_item.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /line_items/1
	# PATCH/PUT /line_items/1.json
	def update
		respond_to do |format|
			if @line_item.update(line_item_params)
				format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
				format.json { render :show, status: :ok, location: @line_item }
			else
				format.html { render :edit }
				format.json { render json: @line_item.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /line_items/1
	# DELETE /line_items/1.json
	def destroy
		@line_item.destroy

		respond_to do |format|
			format.html { redirect_to line_items_url, notice: "Req ID: #{@line_item.id} removed." }
			format.json { head :no_content }
		end
	end

	def destroy_related
		fdask
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_line_item
			@line_item = LineItem.find(params[:id])
		end

		def set_current_user
			@user = defined?(current_user) ? current_user : GuestUser
		end

		# Only allow a list of trusted parameters through.
		def line_item_params
			params.require(:line_item).permit(:product_id, :cart_id)
		end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
	def user_top_suggested_tags(n = 3)
		current_user.combine_items.map { |x| x[0].tags.map(&:title) }.flatten.tally
		.sort_by { |x| x[1] }.tap(&:reverse!).map!(&:first).first(n)
		.map! do |x|
			Tag.where(title: x).map(&:product_id).tap(&:uniq!)
			.map! { |y| Product.find(y) unless current_user.includes?(y) }.tap(&:compact!)
		end.reject(&:empty?).tap(&:flatten!).first(5)
	end
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<center><h2>Your Cart</h2></center>

<div id="item-thumbnails">
	<div class="row">
		<div class="col-md-6 col-sm-12 col-lg-4">
			<% @user_items.each.with_index do |x, i| %>
				<div class= "shadow-sm-hover">
					<div class="card mb-3 rounded">
						<%= link_to x[0] do %>
							<div class="img-hover-effect">
								<div class="img-hover-label">
									<i class="fas fa-info-circle"></i>
									More Info
								</div>

								<%= product_image(x[0]) %>
							</div>
						<% end %>

						<div class="card-body mb-1">
							<h5 class="card-title"><%= x[0].title %></h5>

							Quantity: <%= x[1][0] %>

							<p class="card-text">
								<%= format_tags(x[0], 'tags:').html_safe %>
							</p>

							<hr>
							Order Details: <br>

							<% x[1][1].each do |y| %>
								<div class="mb-4">
									<%= print_clock_emoji(y.updated_at.strftime('%H').to_i) %>
									<%= y.updated_at.strftime("%d-%M-%Y") %>
									<%= y.updated_at.strftime("%H:%m") %>
									<br>
									Req ID: <%= y.id %> | Qn: <%= y.quantity %>
									<br>

									<%= link_to y, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "btn-outline-primary-animated", "data-content": "Remove" do %>
										<%= image_tag 'delete_cart_item.svg', width: '24px' %>
									<% end %>
								</div>
							<% end %>
						</div>
					</div>
				</div>
			<% end %>
		</div>

		<div class="col-md-2 col-lg-4 col-sm-0">
		</div>

		<div class="col-md-4 col-lg-4 col-sm-12">
			100% Purchase Protection
			<div class="card">
				<div class="card-body">
					Subtotal: 2 items<br>
					Total Price: Rs. <%=  %><br>
					<%= link_to '', products_checkout_all_path, class: 'btn-outline-success-animated', %s(data-content) => 'Proceed to Checkout' %>
				</div>
			</div>

			<h4>Other items you might be interested in:</h4>
			<% user_top_suggested_tags(3).each do |x| %>
				<%= link_to x, class: 'link-no-style' do %>
					<div class="card mb-3">
						<div class="card-body">
							<div class="img-hover-effect">
								<div class="img-hover-label">
									<i class="fas fa-info-circle"></i>
									More Info
								</div>

								<% if x.thumbnail.url %>
									<%= image_tag x.thumbnail.thumbnail!.url, class: 'card-img-top' %>
								<% else %>
									<div class="no-img-label">No Preview Available!</div>
								<% end %>
							</div>

							<div style="font-weight: 1000 ; font-size: 20px"><%= x.title %></div>
							Price: <%= rs_tag(x.price) %>
							<%= x %>
							<div class="rating-wrapper-all">
								<div class="rating-wrapper">
									<div class="rating-div"></div>
									<%= image_tag 'stars.png', class: 'rating' %>
								</div>

								<span class="ratings-label">134</span>
							</div>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>